### ISSUE TITLE
How do i use it?

### ISSUE THREAD

**Issue by BaconBros** [notkohlrexo/Discord-Token-Stealer#1]
So idk how i use the software to showcase my friends.

**Comment by JustPandaPan** [comment]
plz help

**Comment by JustPandaPan** [comment]
idk too

**Comment by Anti-kek** [comment]
yeah idk how to use it as well

**Comment by RSK-RISK** [comment]
imlement this into another program or script and have them run it

**Comment by m-Phoenix852** [comment]
how to use it bruh?

**Comment by Romeo-Johan74** [comment]
You need to understand the C# (the language used for the program) ^^

**Comment by m-Phoenix852** [comment]
> You need to understand the C# (the language used for the program) ^^

Why don't you just close this issue now
