### ISSUE TITLE
How

### ISSUE THREAD

**Issue by Aezene** [notkohlrexo/Discord-Token-Stealer#10]
How do i even use this, discord does not support the file type

**Comment by J0k3r-Squ4d** [comment]
use visual studio code to compile the .sln (solution) file into an exe

**Comment by IsMaix** [comment]
> use visual studio code to compile the .sln (solution) file into an exe

When I try to do that it gives me this error:

Unable to copy file "obj\Debug\Discord Token Stealer.exe" to "bin\Debug\Discord Token Stealer.exe". Could not find file 'obj\Debug\Discord Token Stealer.exe'.	Discord Token Stealer

**Comment by IsMaix** [comment]
Oh nvm, my antivirus detects it as a trojan lol

**Comment by J0k3r-Squ4d** [comment]
> Oh nvm, my antivirus detects it as a trojan lol

Add an exception in the antivirus for the token stealer. That should solve the issue

**Comment by IsMaix** [comment]
> > Oh nvm, my antivirus detects it as a trojan lol
> 
> Add an exception in the antivirus for the token stealer. That should solve the issue

Well yeah, I did that but then realized that it's gonna be pretty useless if my friends have the same antivirus which I recommended to them. It's just gonna detect it
