### ISSUE TITLE
Not Working. (Exception File Not Found)

### ISSUE THREAD

**Issue by 0xyg3n** [notkohlrexo/Discord-Token-Stealer#2]
![image](https://user-images.githubusercontent.com/7093928/86357605-c0800680-bc76-11ea-8467-f46089008f80.png)

**Comment by notkohlrexo** [comment]
The path of leveldb might have changed or you don't have chrome installed. But I think the Discord Token Stealer is outdated anyways, I don't recommend using it anymore.
