### ISSUE TITLE
Start file?

### ISSUE THREAD

**Issue by mrgamer45** [notkohlrexo/Discord-Token-Stealer#5]
I would think that the start file is Program.cs, but I don't have anything installed that can run it besides text editors, so what is it that I need to install?(srry I don't know much about C# I'm more of a Python person)

**Comment by BruzzTheHuzz0** [comment]
You need to use Visual Studio to build it into an EXE.

**Comment by JULI4N0** [comment]
how do u build it into a exe

**Comment by monkecion** [comment]
watch youtube tutorials thats it

**Comment by zisouuu** [comment]
can i get a link please ?

**Comment by AstroOrbis** [comment]
Bump

**Comment by mrgamer45** [comment]
wdym? i still dont know how to convert cs to exe

**Comment by danekxd** [comment]
You Can Build it inside Visual Studo

**Comment by mrgamer45** [comment]
how? I don't see anything about that in Visual Studio Code (the thing I have rn)

**Comment by AstroOrbis** [comment]
Visual Studio and VSC are 2 different things, i learnt the hard way

**Comment by mrgamer45** [comment]
i was afraid you would say that. i hate the Microsoft version lol

**Comment by AstroOrbis** [comment]
I got it just so I can be prepared for anything :p

**Comment by danekxd** [comment]
VSC doesn't have build feature, install the Visual Studio 2019 Community and watch this video how to build it https://youtu.be/zSl1PgmhpwY

**Comment by mrgamer45** [comment]
@danekxd it says Discord Token Stealer (unloaded) in solutions when I try to do the sln file

**Comment by mrgamer45** [comment]
Finally figured it out, just had to install the dotnet thingy.
