### ISSUE TITLE
Does this work with MacOS?

### ISSUE THREAD

**Issue by AstroOrbis** [notkohlrexo/Discord-Token-Stealer#7]

**Comment by GILLESMaster** [comment]
Lol, depends on ur skills to edit the script

**Comment by AstroOrbis** [comment]
Ok how the heck do I check what OS the script is on then :p

**Comment by AstroOrbis** [comment]
@notkohlrexo would it be possible to use [this](https://stackoverflow.com/questions/5116977/how-to-check-the-os-version-at-runtime-e-g-on-windows-or-linux-without-using) to grab on multiple platforms?

**Comment by Pr0xyblade** [comment]
god the amount of retarded skids on these repos

**Comment by notkohlrexo** [comment]
> god the amount of retarded skids on these repos

lol

**Comment by AstroOrbis** [comment]
Allright so now I know some C#, I was stupid back then :p
