### ISSUE TITLE
i use windows 10 and i cant find the executable file that should activate it.

### ISSUE THREAD

**Issue by EnderBossPro-pvp** [notkohlrexo/Discord-Token-Stealer#9]
i use windows 10 and i can't find the executable file that should activate it, what file should i be looking for? and is my problem it doesn't work on windows 10?

**Comment by kunaibox** [comment]
compile it lol

**Comment by lolSteeeeve** [comment]
> i use windows 10 and i can't find the executable file that should activate it, what file should i be looking for? and is my problem it doesn't work on windows 10?

__lmfao u need to compile it first__
